#!/bin/bash
git config --global color.diff always
git config --global alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
git config --global core.excludesfile ~/.gitignore_global
git clone git://github.com/ndbroadbent/scm_breeze.git ~/git/scm_breeze
~/git/scm_breeze/install.sh
# source ~/.bash_profile
