#!/bin/bash

dir="$( cd "$( dirname "$0" )" && pwd )"

function link() {
    src=$dir/$1/$2
    tgt=~/.$2
    [ -h $tgt ] && rm $tgt
    ln -s $src $tgt
    [ $? -eq 0 ] && echo "[OK] link $2" || echo "[FAIL] link $2"
}

function link_files() {
    link bash bash_profile
    link bash bashrc
    link git gitignore_global
    link tmux tmux.conf
    link tmux tmux-osx.conf
    link vim vim
    link vim vimrc
}

function vim_config() {
    git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
}

function brew_install() {
    # install Xcode and command line tools
    brew install git
    brew install macvim --override-system-vim
    brew install tmux
    brew install tree
}

function setup() {
    defaults write -g InitialKeyRepeat -int 15 # normal minimum is 15 (225 ms)
    defaults write -g KeyRepeat -int 2 # normal minimum is 2 (30 ms)
}

link_files
