#!/bin/bash

DIR="$( cd "$( dirname "$0" )" && pwd )"

function link() {
    SOURCE=$DIR/$1
    TARGET=~/.$1
    if [ -s "$TARGET" ]; then
        rm $TARGET
    fi
    ln -s $SOURCE $TARGET
}

function link_files() {
    link vimrc
    link vim
    link bash_profile
    link tmux.conf
}

function brew_install() {
    # install Xcode and command line tools
    brew install git
    brew install macvim --override-system-vim
    brew install tmux
    brew install tree
}

link_files
