[ids]
*

[main]
leftalt = layer(ctrl)
leftmeta = layer(alt)
leftcontrol = layer(meta)

capslock = overload(caps, esc)
rightalt = layer(vim)

[ctrl:C]
[alt:A]
[meta:M]

[caps:C]
n = down
p = up
f = right
b = left
a = home
e = end

[vim]
h = left
j = down
k = up
l = right

