"vundle
set nocompatible
filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
filetype plugin indent on
Bundle 'gmarik/vundle'
"fancy status
Bundle 'bling/vim-airline'
"file navigation
Bundle 'scrooloose/nerdtree'
Bundle 'kien/ctrlp.vim'
"format
Bundle 'initrc/neinspace'
"git
Bundle 'tpope/vim-fugitive'
"html
Bundle 'rstacruz/sparkup'
"run code
Bundle 'initrc/runner'
"search
Bundle 'rking/ag.vim'
"syntax
Bundle 'scrooloose/syntastic'

"leader
let mapleader=','
let maplocalleader='\\'

"airline
let g:airline_powerline_fonts=1

"neinspace
nnoremap <silent> <leader>w :NeinspaceClear<CR>

"nerdtree
autocmd vimenter * if !argc() | NERDTree | endif
autocmd bufenter * if (winnr('$') == 1 && exists('b:NERDTreeType') && b:NERDTreeType == 'primary') | q | endif
let NERDTreeIgnore=['\.pyc$', '\.class$']
nnoremap <silent> <leader>f :NERDTreeToggle<CR>

"ctrlp
let g:ctrlp_map='//'
let g:ctrlp_working_path_mode='a'
let g:ctrlp_user_command='find %s -type f'
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/]\.(git|hg|svn)$',
  \ 'file': '\v\.(exe|so|dll|class|swp)$',
  \ 'link': 'some_bad_symbolic_links',
  \ }

"runner
nnoremap <silent> <leader>r :RunnerRun<CR>

"syntastic
let g:syntastic_python_checkers=['flake8']
let g:syntastic_javascript_checkers=['jshint']
let g:syntastic_java_checkers = ['checkstyle']

"spell checker
nnoremap <silent> <leader>s :set spell!<CR>

"ui
let &t_Co=256
colorscheme spring
syn on
set number
set laststatus=2
set visualbell
hi MatchParen cterm=bold ctermbg=none ctermfg=red

"clipboard
set clipboard+=unnamed

"tab
set tabstop=4
set shiftwidth=4
set expandtab

"indent
set ai
set autoindent
set smartindent
au FileType python setl nosmartindent
filetype plugin indent on

"search
set hlsearch
set incsearch
set showmatch
set ignorecase
set smartcase

"tabstop=2
au BufNewFile,BufRead *.vim,*.html,*.css,*.js,*.json set tabstop=2
au BufNewFile,BufRead *.vim,*.html,*.css,*.js,*.json set shiftwidth=2

"encoding
set fileencodings=utf-8,gb2312,gbk,gb18030

"mapping

"esc is too far away
inoremap jk <Esc>
"H and L to start and end of line
noremap H ^
noremap L $
"K and J to page up and down
noremap K <C-b>M
noremap J <C-f>M
"+ to join lines (J is remapped)
noremap + J
"U to redo
nnoremap U <C-r>
"window
nnoremap <silent> gh :wincmd h<CR>
nnoremap <silent> gj :wincmd j<CR>
nnoremap <silent> gk :wincmd k<CR>
nnoremap <silent> gl :wincmd l<CR>
nnoremap <silent> gp :wincmd p<CR>
nnoremap <silent> g= :wincmd =<CR>
nnoremap <silent> gx :wincmd x<CR>
"paste
nnoremap <silent> <leader>p :set paste!<CR>

"ignore
set wildignore=*/tmp/*,*.pyc,*.o,*~,*.so,*.swp,*.zip,*.jpg,*.png,*.gif
